-- MySQL Script generated by MySQL Workbench
-- Fri Jun 30 12:09:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurante` (
  `id_restaurante` INT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `numero_telefonol` INT NOT NULL,
  `horario_apertura` DATETIME NOT NULL,
  `horario_cierre` DATETIME NOT NULL,
  PRIMARY KEY (`id_restaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mesa` (
  `id_mesa` INT NOT NULL,
  `capacidad` INT NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_mesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleado_mesero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado_mesero` (
  `id_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `posicion` VARCHAR(45) NOT NULL,
  `salario` INT NOT NULL,
  `fecha_contratacion` DATETIME NOT NULL,
  `restaurante_id_restaurante` INT NOT NULL,
  PRIMARY KEY (`id_empleado`, `restaurante_id_restaurante`),
  INDEX `fk_empleado_mesero_restaurante1_idx` (`restaurante_id_restaurante` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_mesero_restaurante1`
    FOREIGN KEY (`restaurante_id_restaurante`)
    REFERENCES `mydb`.`restaurante` (`id_restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `numero_telefono` INT(45) NULL,
  `mesa_id_mesa` INT NOT NULL,
  `restaurante_id_restaurante` INT NOT NULL,
  `empleado_mesero_id_empleado` INT NOT NULL,
  `empleado_mesero_restaurante_id_restaurante` INT NOT NULL,
  PRIMARY KEY (`id_cliente`,`restaurante_id_restaurante`, `empleado_mesero_id_empleado`, `empleado_mesero_restaurante_id_restaurante`),
  INDEX `fk_cliente_mesa1_idx` (`mesa_id_mesa` ASC) VISIBLE,
  INDEX `fk_cliente_restaurante1_idx` (`restaurante_id_restaurante` ASC) VISIBLE,
  INDEX `fk_cliente_empleado_mesero1_idx` (`empleado_mesero_id_empleado` ASC, `empleado_mesero_restaurante_id_restaurante` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_mesa1`
    FOREIGN KEY (`mesa_id_mesa`)
    REFERENCES `mydb`.`mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_restaurante1`
    FOREIGN KEY (`restaurante_id_restaurante`)
    REFERENCES `mydb`.`restaurante` (`id_restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_empleado_mesero1`
    FOREIGN KEY (`empleado_mesero_id_empleado` , `empleado_mesero_restaurante_id_restaurante`)
    REFERENCES `mydb`.`empleado_mesero` (`id_empleado` , `restaurante_id_restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id_pedido` INT NOT NULL,
  `fecha_pedido` DATETIME NOT NULL,
  `hora_pedido` DATETIME NOT NULL,
  `estado_pedido` VARCHAR(45) NOT NULL,
  `total_pedido` VARCHAR(45) NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `cliente_` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_id_cliente` ASC, `cliente_` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_id_cliente` , `cliente_`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id_producto` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `pedido_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_producto_pedido1_idx` (`pedido_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_producto_pedido1`
    FOREIGN KEY (`pedido_id_pedido`)
    REFERENCES `mydb`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
