-- MySQL Script generated by MySQL Workbench
-- Fri Jun 30 14:22:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiante` (
  `idestudiante` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `direccion` INT NOT NULL,
  PRIMARY KEY (`idestudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia` (
  `idmateria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `numero_creditos` INT NOT NULL,
  `estudiante_idestudiante` INT NOT NULL,
  PRIMARY KEY (`idmateria`, `estudiante_idestudiante`),
  INDEX `fk_materia_estudiante_idx` (`estudiante_idestudiante` ASC) VISIBLE,
  CONSTRAINT `fk_materia_estudiante`
    FOREIGN KEY (`estudiante_idestudiante`)
    REFERENCES `mydb`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inscripcion` (
  `idinscripcion` INT NOT NULL,
  `fecha_inscripcion` DATETIME NOT NULL,
  `estudiante_idestudiante` INT NOT NULL,
  `materia_idmateria` INT NOT NULL,
  `materia_estudiante_idestudiante` INT NOT NULL,
  PRIMARY KEY (`idinscripcion`, `estudiante_idestudiante`, `materia_idmateria`, `materia_estudiante_idestudiante`),
  INDEX `fk_inscripcion_estudiante1_idx` (`estudiante_idestudiante` ASC) VISIBLE,
  INDEX `fk_inscripcion_materia1_idx` (`materia_idmateria` ASC, `materia_estudiante_idestudiante` ASC) VISIBLE,
  CONSTRAINT `fk_inscripcion_estudiante1`
    FOREIGN KEY (`estudiante_idestudiante`)
    REFERENCES `mydb`.`estudiante` (`idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_materia1`
    FOREIGN KEY (`materia_idmateria` , `materia_estudiante_idestudiante`)
    REFERENCES `mydb`.`materia` (`idmateria` , `estudiante_idestudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
